version: '2'

services:
#-------------------------------Nginx-Proxy------------------
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - certData:/etc/nginx/certs:ro
#    networks:
 #     - proxy-tier
    restart: always

  nginx-gen:
    image: jwilder/docker-gen
 #   build: 
#      - label:com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen
    container_name: nginx-gen
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    volumes_from:
      - nginx-proxy
      #-only-exposed
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: always
 #----------------------------Letsencrypt-----------------
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - certData:/etc/nginx/certs:rw
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
    restart: always
  #--------------- Dummy Webmail Container for Certificate Generation ------
  webmail:
    image: nginx:alpine
    container_name: webmail
    volumes_from:
      - nginx-proxy
    environment: 
      - VIRTUAL_HOST=mail.${DOMAINNAME}
      #- VIRTUAL_NETWORK=nginx-proxy-net
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=mail.${DOMAINNAME}
      - LETSENCRYPT_EMAIL=postmaster@${DOMAINNAME}
    restart: always
#----------------- Downloadgateway----------------------------
  downloadgateway:
    image: nginx:alpine
    container_name: downloads
    hostname: downloads
    domainname: ${DOMAINNAME}
    environment:
      - VIRTUAL_HOST=downloads.${DOMAINNAME}
      - VIRTUAL_PORT=80
     # - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=downloads.${DOMAINNAME}
      - LETSENCRYPT_EMAIL=postmaster@${DOMAINNAME}
      - NGINX_SHARED_SECRET=${NGINX_SHARED_SECRET}
    volumes:
      - nginxdata:/usr/share/nginx/downloads:ro
      - ./downloadgateway/conf.d/:/tmp/conf.d/
      - ./downloadgateway/contrib/:/usr/local/bin/
    entrypoint: /usr/local/bin/start_nginx.sh

   # restart: always

#-----------------------------MAIL-----------------------------------------------------------------------------------------
  mail:
    image: docker-mailserver:latest
    build:
        context: ./mailserver/
        dockerfile: Dockerfile
    hostname: mail
    domainname: ${DOMAINNAME}
    container_name: mail
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - ./mailserver/config/:/tmp/docker-mailserver/
      - nginxdata:/var/attachments
      - certData:/etc/letsencrypt/live/
      - ./mailserver/gpg-mailgate/:/var/gpgmailgate/
      - mailattachments:/var/resilio
  #    - ./mailserver/config/gpg-mailgate.conf:/etc/gpg-mailgate.conf
    environment:
      - ENABLE_SPAMASSASSIN=${ENABLE_SPAMASSASSIN}
      - ENABLE_CLAMAV=${ENABLE_CLAMAV}
      - ENABLE_FAIL2BAN=${ENABLE_FAIL2BAN}
      - ENABLE_POSTGREY=${ENABLE_POSTGREY}
      - ONE_DIR=${ONE_DIR}
      - DMS_DEBUG=${DMS_DEBUG}
      - PERMIT_DOCKER=${PERMIT_DOCKER}
      - POSTMASTER_ADDRESS=${POSTMASTER_ADDRESS}
      - SSL_TYPE=letsencrypt
      - NGINX_SHARED_SECRET=${NGINX_SHARED_SECRET}
      - NGINX_DOWNLOAD_DOMAIN=downloads.${DOMAINNAME}
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always

#-------------------- Resilio Sync -------------------------------------------
  resilio-sync:
    image: resilio-sync:latest
    container_name: sync
    build:
        context: ./resilio-sync/
        dockerfile: Dockerfile
    domainname: ${DOMAINNAME}
    ports:
      - "55555"
    environment:
      - DEVICE_NAME=${DEVICE_NAME}
    volumes:
      - syncdata:/usr/share/resilio-sync/
      - mailattachments:/usr/share/attachments/
      - ./resilio-sync/config/:/tmp/resilio-config/

   # restart: always
 
#-------------------- Webseiten ----------------------------------------------
  website:
    image: nginx:alpine
    container_name: web
    domainname: ${DOMAINNAME}
    environment:
      - VIRTUAL_HOST=${DOMAINNAME}
      #- VIRTUAL_NETWORK=nginx-proxy-net
      - VIRTUAL_PORT=80
     # - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=${DOMAINNAME}
      - LETSENCRYPT_EMAIL=postmaster@${DOMAINNAME}
    volumes:
      - ./website/conf.d/:/etc/nginx/conf.d:ro
      - ./website/content/:/usr/share/nginx/html:ro

   # restart: always
   
volumes:
  mailattachments:
    driver: local
  syncdata:
    driver: local
  maildata:
    driver: local
  mailstate:
    driver: local
  nginxdata:
    driver: local
  certData:
    driver: local
